INSERT INTO addresses (description, client_id) VALUES ('123 Main St', 1);
INSERT INTO addresses (description, client_id) VALUES ('456 Elm St', 1);
INSERT INTO addresses (description, client_id) VALUES ('789 Oak St', 1);
INSERT INTO addresses (description, client_id) VALUES ('101 Pine St', 2);
INSERT INTO addresses (description, client_id) VALUES ('202 Maple St', 2);
INSERT INTO addresses (description, client_id) VALUES ('303 Birch St', 2);
INSERT INTO addresses (description, client_id) VALUES ('404 Cedar St', 1);
INSERT INTO addresses (description, client_id) VALUES ('505 Walnut St', 1);
INSERT INTO addresses (description, client_id) VALUES ('606 Cherry St', 3);
INSERT INTO addresses (description, client_id) VALUES ('707 Ash St', 3);
INSERT INTO addresses (description, client_id) VALUES ('808 Beech St', 4);
INSERT INTO addresses (description, client_id) VALUES ('909 Fir St', 1);
INSERT INTO addresses (description, client_id) VALUES ('1010 Spruce St', 3);
INSERT INTO addresses (description, client_id) VALUES ('1111 Willow St', 1);
INSERT INTO addresses (description, client_id) VALUES ('1212 Poplar St', 5);
INSERT INTO addresses (description, client_id) VALUES ('1313 Cypress St', 1);
INSERT INTO addresses (description, client_id) VALUES ('1414 Dogwood St', 4);
INSERT INTO addresses (description, client_id) VALUES ('1515 Magnolia St', 1);
INSERT INTO addresses (description, client_id) VALUES ('1616 Palm St', 1);
INSERT INTO addresses (description, client_id) VALUES ('1717 Redwood St', 6);
INSERT INTO addresses (description, client_id) VALUES ('1818 Sequoia St', 1);
INSERT INTO addresses (description, client_id) VALUES ('1919 Hickory St', 6);
INSERT INTO addresses (description, client_id) VALUES ('2020 Sycamore St', 3);
INSERT INTO addresses (description, client_id) VALUES ('2121 Chestnut St', 5);
INSERT INTO addresses (description, client_id) VALUES ('2222 Fir St', 1);
INSERT INTO addresses (description, client_id) VALUES ('2323 Hemlock St', 1);

INSERT INTO clients (name, last_name) VALUES ('John', 'Doe');
INSERT INTO clients (name, last_name) VALUES ('Jane', 'Doe');
INSERT INTO clients (name, last_name) VALUES ('Alice', 'Smith');
INSERT INTO clients (name, last_name) VALUES ('Bob', 'Johnson');
INSERT INTO clients (name, last_name) VALUES ('Charlie', 'Brown');
INSERT INTO clients (name, last_name) VALUES ('Eve', 'Davis');
INSERT INTO clients (name, last_name) VALUES ('Frank', 'Miller');
INSERT INTO clients (name, last_name) VALUES ('Grace', 'Hopper');
INSERT INTO clients (name, last_name) VALUES ('Hank', 'Williams');

INSERT INTO invoices (client_id, description, total) VALUES (1, 'Invoice 1.0', 100.0);
INSERT INTO invoices (client_id, description, total) VALUES (1, 'Invoice 1.1', 200.0);
INSERT INTO invoices (client_id, description, total) VALUES (1, 'Invoice 1.2', 250.0);
INSERT INTO invoices (client_id, description, total) VALUES (2, 'Invoice 2.0', 150.0);
INSERT INTO invoices (client_id, description, total) VALUES (2, 'Invoice 2.1', 175.0);
INSERT INTO invoices (client_id, description, total) VALUES (3, 'Invoice 3.0', 200.0);
INSERT INTO invoices (client_id, description, total) VALUES (3, 'Invoice 3.1', 225.0);
INSERT INTO invoices (client_id, description, total) VALUES (4, 'Invoice 4.0', 300.0);
INSERT INTO invoices (client_id, description, total) VALUES (4, 'Invoice 4.1', 325.0);
INSERT INTO invoices (client_id, description, total) VALUES (5, 'Invoice 5.0', 400.0);
INSERT INTO invoices (client_id, description, total) VALUES (5, 'Invoice 5.1', 425.0);
INSERT INTO invoices (client_id, description, total) VALUES (6, 'Invoice 6.0', 500.0);
INSERT INTO invoices (client_id, description, total) VALUES (6, 'Invoice 6.1', 525.0);
INSERT INTO invoices (client_id, description, total) VALUES (7, 'Invoice 7.0', 600.0);
INSERT INTO invoices (client_id, description, total) VALUES (7, 'Invoice 7.1', 625.0);